# Generated by Django 3.2 on 2021-05-01 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='buildingType',
        ),
    ]
