# Generated by Django 3.2 on 2021-04-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210430_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
