# Generated by Django 3.2 on 2021-05-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolio_buildingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='buildingType',
            field=models.CharField(blank=True, choices=[('C', '상업시설'), ('R', '주거복합'), ('H', '주택')], max_length=1, null=True),
        ),
    ]
