# Generated by Django 3.2 on 2021-04-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='type',
            field=models.CharField(default='주거복합', max_length=50),
        ),
    ]
