# Generated by Django 3.2 on 2021-04-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='area',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='service',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
