# Generated by Django 3.2 on 2021-05-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfolioimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='buildingType',
            field=models.CharField(blank=True, choices=[('C', '상업시설'), ('R', '주거복합'), ('H', '주택')], default='C', max_length=1, null=True),
        ),
    ]
